// Code generated by protoc-gen-go. DO NOT EDIT.
// source: eventstore.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	EventId              int64    `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId          int64    `protobuf:"varint,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,4,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventData            string   `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	ExData               string   `protobuf:"bytes,6,opt,name=ex_data,json=exData,proto3" json:"ex_data,omitempty"`
	Channel              string   `protobuf:"bytes,7,opt,name=channel,proto3" json:"channel,omitempty"`
	Stream               string   `protobuf:"bytes,8,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *Event) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *Event) GetAggregateId() int64 {
	if m != nil {
		return m.AggregateId
	}
	return 0
}

func (m *Event) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *Event) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func (m *Event) GetExData() string {
	if m != nil {
		return m.ExData
	}
	return ""
}

func (m *Event) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *Event) GetStream() string {
	if m != nil {
		return m.Stream
	}
	return ""
}

type Response struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type EventFilter struct {
	EventId              int64    `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AggregateId          int64    `protobuf:"varint,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventFilter) Reset()         { *m = EventFilter{} }
func (m *EventFilter) String() string { return proto.CompactTextString(m) }
func (*EventFilter) ProtoMessage()    {}
func (*EventFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{2}
}

func (m *EventFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventFilter.Unmarshal(m, b)
}
func (m *EventFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventFilter.Marshal(b, m, deterministic)
}
func (m *EventFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventFilter.Merge(m, src)
}
func (m *EventFilter) XXX_Size() int {
	return xxx_messageInfo_EventFilter.Size(m)
}
func (m *EventFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_EventFilter.DiscardUnknown(m)
}

var xxx_messageInfo_EventFilter proto.InternalMessageInfo

func (m *EventFilter) GetEventId() int64 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventFilter) GetAggregateId() int64 {
	if m != nil {
		return m.AggregateId
	}
	return 0
}

type EventResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventResponse) Reset()         { *m = EventResponse{} }
func (m *EventResponse) String() string { return proto.CompactTextString(m) }
func (*EventResponse) ProtoMessage()    {}
func (*EventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00783576c07562d6, []int{3}
}

func (m *EventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventResponse.Unmarshal(m, b)
}
func (m *EventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventResponse.Marshal(b, m, deterministic)
}
func (m *EventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventResponse.Merge(m, src)
}
func (m *EventResponse) XXX_Size() int {
	return xxx_messageInfo_EventResponse.Size(m)
}
func (m *EventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventResponse proto.InternalMessageInfo

func (m *EventResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*EventFilter)(nil), "pb.EventFilter")
	proto.RegisterType((*EventResponse)(nil), "pb.EventResponse")
}

func init() { proto.RegisterFile("eventstore.proto", fileDescriptor_00783576c07562d6) }

var fileDescriptor_00783576c07562d6 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0xad, 0xcd, 0xc7, 0xa4, 0x15, 0x59, 0x44, 0x57, 0x41, 0x48, 0x03, 0x42, 0x4e, 0x39,
	0x44, 0xf0, 0xea, 0xc1, 0x0f, 0x28, 0xde, 0x52, 0xef, 0x65, 0x93, 0x0c, 0x31, 0x50, 0x93, 0x65,
	0x77, 0x95, 0xf6, 0x87, 0x7b, 0x97, 0xcc, 0xb6, 0xa9, 0x28, 0x78, 0xcb, 0xbc, 0xf7, 0xe6, 0x4d,
	0xf6, 0x3d, 0x38, 0xc5, 0x4f, 0x6c, 0x8d, 0x36, 0x9d, 0xc2, 0x54, 0xaa, 0xce, 0x74, 0x6c, 0x24,
	0x8b, 0xf8, 0xcb, 0x81, 0xc9, 0x53, 0x4f, 0xb0, 0x4b, 0xf0, 0x49, 0xb1, 0x6a, 0x2a, 0xee, 0x44,
	0x4e, 0x32, 0xce, 0x3d, 0x9a, 0x17, 0x15, 0xbb, 0x06, 0xb0, 0x94, 0xd9, 0x4a, 0xe4, 0xa3, 0xc8,
	0x49, 0x82, 0x3c, 0x20, 0xe4, 0x75, 0x2b, 0x91, 0xcd, 0x61, 0x2a, 0xea, 0x5a, 0x61, 0x2d, 0x0c,
	0xf6, 0xdb, 0x63, 0xda, 0x0e, 0x07, 0x6c, 0x51, 0xb1, 0x1b, 0x38, 0x39, 0x48, 0xc8, 0xe5, 0x98,
	0x5c, 0x66, 0x03, 0x4a, 0x4e, 0xc3, 0xa1, 0x4a, 0x18, 0xc1, 0x27, 0x3f, 0x0e, 0x3d, 0x0a, 0x23,
	0xd8, 0x05, 0x78, 0xb8, 0xb1, 0x9c, 0x4b, 0x9c, 0x8b, 0x1b, 0x22, 0x38, 0x78, 0xe5, 0x9b, 0x68,
	0x5b, 0x5c, 0x73, 0x8f, 0x88, 0xfd, 0xc8, 0xce, 0xc1, 0xd5, 0x46, 0xa1, 0x78, 0xe7, 0xbe, 0xdd,
	0xb0, 0x53, 0x7c, 0x0f, 0x7e, 0x8e, 0x5a, 0x76, 0xad, 0xa6, 0xab, 0x8d, 0x5e, 0xe9, 0x8f, 0xb2,
	0x44, 0xad, 0xe9, 0xed, 0x7e, 0x1e, 0x34, 0x7a, 0x69, 0x01, 0x76, 0x06, 0x13, 0x54, 0xaa, 0x53,
	0xbb, 0x87, 0xdb, 0x21, 0x7e, 0x81, 0x90, 0x72, 0x7b, 0x6e, 0xd6, 0x06, 0xd5, 0x7f, 0xe9, 0xfd,
	0x8e, 0x67, 0xf4, 0x27, 0x9e, 0x38, 0x83, 0x19, 0x99, 0x0d, 0xbf, 0x34, 0x07, 0xd7, 0xd6, 0xc5,
	0x9d, 0x68, 0x9c, 0x84, 0x59, 0x90, 0xca, 0x22, 0xb5, 0x92, 0x1d, 0x91, 0xdd, 0x01, 0x10, 0xb0,
	0xec, 0x1b, 0x65, 0x09, 0x84, 0x0f, 0x0a, 0x85, 0x41, 0x5b, 0xe6, 0x41, 0x7f, 0x35, 0xed, 0x3f,
	0xf7, 0xc6, 0xf1, 0x51, 0xe1, 0x52, 0xf9, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x8c,
	0xb3, 0x00, 0x10, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EventStoreClient is the client API for EventStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventStoreClient interface {
	// Create a new event to the event store
	CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error)
}

type eventStoreClient struct {
	cc *grpc.ClientConn
}

func NewEventStoreClient(cc *grpc.ClientConn) EventStoreClient {
	return &eventStoreClient{cc}
}

func (c *eventStoreClient) CreateEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.EventStore/CreateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventStoreServer is the server API for EventStore service.
type EventStoreServer interface {
	// Create a new event to the event store
	CreateEvent(context.Context, *Event) (*Response, error)
}

func RegisterEventStoreServer(s *grpc.Server, srv EventStoreServer) {
	s.RegisterService(&_EventStore_serviceDesc, srv)
}

func _EventStore_CreateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventStoreServer).CreateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.EventStore/CreateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventStoreServer).CreateEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

var _EventStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventStore",
	HandlerType: (*EventStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEvent",
			Handler:    _EventStore_CreateEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventstore.proto",
}
