// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GudpUserCreateCommand struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	Mobile               string   `protobuf:"bytes,3,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Pwd                  string   `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`
	SecretKey            string   `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GudpUserCreateCommand) Reset()         { *m = GudpUserCreateCommand{} }
func (m *GudpUserCreateCommand) String() string { return proto.CompactTextString(m) }
func (*GudpUserCreateCommand) ProtoMessage()    {}
func (*GudpUserCreateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GudpUserCreateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GudpUserCreateCommand.Unmarshal(m, b)
}
func (m *GudpUserCreateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GudpUserCreateCommand.Marshal(b, m, deterministic)
}
func (m *GudpUserCreateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GudpUserCreateCommand.Merge(m, src)
}
func (m *GudpUserCreateCommand) XXX_Size() int {
	return xxx_messageInfo_GudpUserCreateCommand.Size(m)
}
func (m *GudpUserCreateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_GudpUserCreateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_GudpUserCreateCommand proto.InternalMessageInfo

func (m *GudpUserCreateCommand) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *GudpUserCreateCommand) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *GudpUserCreateCommand) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GudpUserCreateCommand) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GudpUserCreateCommand) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *GudpUserCreateCommand) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func init() {
	proto.RegisterType((*GudpUserCreateCommand)(nil), "pb.GudpUserCreateCommand")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x5a, 0xca, 0xc8, 0x25, 0xea,
	0x5e, 0x9a, 0x52, 0x10, 0x5a, 0x9c, 0x5a, 0xe4, 0x5c, 0x94, 0x9a, 0x58, 0x92, 0xea, 0x9c, 0x9f,
	0x9b, 0x9b, 0x98, 0x97, 0x22, 0x24, 0xc0, 0xc5, 0x5c, 0x9a, 0x99, 0x22, 0xc1, 0xa8, 0xc0, 0xa8,
	0xc1, 0x1c, 0x04, 0x62, 0x0a, 0x49, 0x73, 0x71, 0xe6, 0x65, 0x26, 0x67, 0xc7, 0xe7, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x80, 0x04, 0xfc, 0x12, 0x73, 0x53, 0x85,
	0xc4, 0xb8, 0xd8, 0x72, 0xf3, 0x93, 0x32, 0x73, 0x52, 0x25, 0x98, 0xc1, 0x32, 0x50, 0x9e, 0x90,
	0x08, 0x17, 0x6b, 0x6a, 0x6e, 0x62, 0x66, 0x8e, 0x04, 0x0b, 0x58, 0x18, 0xc2, 0x01, 0x19, 0x5e,
	0x50, 0x9e, 0x22, 0xc1, 0x0a, 0x16, 0x03, 0x31, 0x85, 0x64, 0xb9, 0xb8, 0x8a, 0x53, 0x93, 0x8b,
	0x52, 0x4b, 0xe2, 0xb3, 0x53, 0x2b, 0x25, 0xd8, 0xc0, 0x12, 0x9c, 0x10, 0x11, 0xef, 0xd4, 0xca,
	0x24, 0x36, 0xb0, 0x93, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x55, 0x45, 0x35, 0xef, 0xc0,
	0x00, 0x00, 0x00,
}
