###############################################################################
#
#    base section
#
###############################################################################

### health
GET http://127.0.0.1:18080/health

###############################################################################
#
#    user section
#
###############################################################################

### 创建用户
POST http://127.0.0.1:18080/api/v1/user
Content-Type: application/json

{
    "nick_name": "ministor",
    "mobile": "138"
}

### 获取用户列表
GET http://127.0.0.1:18080/api/v1/user
Content-Type: application/json

{
    
}

### 获取用户
GET http://127.0.0.1:18080/api/v1/user/765897466338869248
Content-Type: application/json

{
    
}